require 'faker'

Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))
Patient.create(name: Faker::Name.name, age: Faker::Number.number(digits: 2), weight: Faker::Number.between(from: 100, to: 400), height: Faker::Number.between(from: 48, to: 96))

Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))
Doctor.create(name: Faker::Name.name, specialty: Specialty.all.sample, location: Faker::Address.city, yrs_experience: Faker::Number.number(digits: 1))

Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)
Appointment.create(doctor_id: Doctor.all.sample.id, patient_id: Patient.all.sample.id, appointment_date: Faker::Date.forward(days:365), appointment_time: Faker::Time.between(from: DateTime.now, to: DateTime.now + 365), appointment_location: Faker::Address.city)

Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))
Patient_History.create(patient_id: Patient.all.sample.id, doctor: Doctor.all.sample.name, treatment: Treatment.all.sample, treatment_date: Faker::Time.between(from: DateTime.now - 1000, to: DateTime.now))

Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)
Appointment_Note.create(appointment_id: Appointment.all.sample.id, note: Note.all.sample, doctor_reccomendation: Doctor.all.sample.name)



